resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: ${yandex_compute_instance.node[*].network_interface.0.nat_ip_address}
    vector:
      hosts:
        vector-01:
          ansible_host: ${yandex_compute_instance.node[*].network_interface.0.nat_ip_address}
  DOC
  filename = "../ansible/inventory/prod.yml"

  depends_on = [
    yandex_compute_instance.node[*],
    yandex_compute_instance.node2
  ]
}